#include "SwitchBusFX.h"
#include <AK/Plugin/MasteringSuiteFXFactory.h>
#include <AK\SoundEngine\Common\AkMemoryMgr.h>
#include <AK\SoundEngine\Common\AkModule.h>

int PresetIndex = 0;

void UWwiseExtensions::ChangeAudioDevicePreset()
{
    int64 AudioDeviceID = 3859886410; int64 FxShareSetID = 930712164; int UserFxIndex = 3;
    // Default Preset,The following IDs are taken from the Wwise_IDs.h file generated by Soundbank packaging

    if (GEngine) // Function Call
    {
        GEngine->AddOnScreenDebugMessage(-1, 5, FColor::Green, TEXT("Function Called::ChangeAudioDevicePreset!"));
        UE_LOG(LogTemp, Display, TEXT("Called Function:ChangeAudioDevicePreset!"));
    }

    PresetIndex++;

    if (PresetIndex == 1)  // Off
    {
        FxShareSetID = 930712164;
        GEngine->AddOnScreenDebugMessage(-1, 5, FColor::Red, TEXT("Preset = Off"));
    }
    else if (PresetIndex == 2) // TV
    {
        FxShareSetID = 1568083719;
        GEngine->AddOnScreenDebugMessage(-1, 5, FColor::Red, TEXT("Preset = TV"));
    }
    else if (PresetIndex == 3) // HomeCinema
    {
        FxShareSetID = 4131355637;
        GEngine->AddOnScreenDebugMessage(-1, 5, FColor::Red, TEXT("Preset = HomeCinema"));
    }
    else if (PresetIndex == 4) // HeadPhones
    {
        FxShareSetID = 880395932;
        GEngine->AddOnScreenDebugMessage(-1, 5, FColor::Red, TEXT("Preset = Headphones"));
    }
    else if (PresetIndex == 5) // SoundBar
    {
        FxShareSetID = 1396549701;
        GEngine->AddOnScreenDebugMessage(-1, 5, FColor::Red, TEXT("Preset = SoundBar"));
    }
    else if (PresetIndex == 6) // NightMode
    {
        FxShareSetID = 2444352864;
        GEngine->AddOnScreenDebugMessage(-1, 5, FColor::Red, TEXT("Preset = NightMode"));
        PresetIndex = 0;
    };

    AK::SoundEngine::SetOutputDeviceEffect(AudioDeviceID, UserFxIndex, FxShareSetID); // Wwise Api,Required for valid use under the ak audio module
    return;
}